name: simply_injector
description: A Dart package based on [Simple Injector library](https://simpleinjector.org/).
  The package is an easy-to-use Dependency Injection (DI) library for Dart.
  Simply Injector Dart Library is easily integrated with Flutter.
  Itâ€™s easy to implement the dependency injection pattern with loosely coupled components using Simply Injector Dart library.

version: 0.1.0
homepage: https://github.com/lamkr/simply_injector
author: Luciano Rodrigues <lamkrodrigues@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
