name: simply_injector
description: An easy-to-use Dependency Injection (DI) library for Dart, inspired and based on Simple Injector library. It is easily integrated with Flutter.
version: 2.1.0
homepage: https://github.com/flutuate/simply_injector

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.3.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
