name: simply_injector
description: An easy-to-use Dependency Injection (DI) library for Dart, inspired and based on Simple Injector library. It is easily integrated with Flutter.

version: 1.1.1
homepage: https://github.com/flutuate/simply_injector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  
dev_dependencies:
  test: any
