name: simply_injector
description: An easy-to-use Dependency Injection (DI) library for Dart, inspired and based on Simple Injector library. It is easily integrated with Flutter.

version: 0.1.3
homepage: https://github.com/flutuate/simply_injector
author: Luciano Rodrigues <flutuate.io@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  
dev_dependencies:
  test: ^1.0.0
